'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
        Option Explicit On

        Imports System

Namespace SyncfusionWpfApp1.Properties

        'This class was auto-generated by the StronglyTypedResourceBuilder
        'class via a tool like ResGen or Visual Studio.
        'To add or remove a member, edit your .ResX file then rerun ResGen
        'with the /str option, or rebuild your VS project.
        '''<summary>
        '''  A strongly-typed resource class, for looking up localized strings, etc.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
        Public Class Resources

            Private Shared resourceMan As Global.System.Resources.ResourceManager

            Private Shared resourceCulture As Global.System.Globalization.CultureInfo

            <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
            Friend Sub New()
                MyBase.New
            End Sub

            '''<summary>
            '''  Returns the cached ResourceManager instance used by this class.
            '''</summary>
            <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
            Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
                Get
                    If Object.ReferenceEquals(resourceMan, Nothing) Then
                        Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                        resourceMan = temp
                    End If
                    Return resourceMan
                End Get
            End Property

            '''<summary>
            '''  Overrides the current thread's CurrentUICulture property for all
            '''  resource lookups using this strongly typed resource class.
            '''</summary>
            <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
            Public Shared Property Culture() As Global.System.Globalization.CultureInfo
                Get
                    Return resourceCulture
                End Get
                Set
                    resourceCulture = Value
                End Set
            End Property

            '''<summary>
            '''  Looks up a localized string similar to wts.ItemName.
            '''</summary>
            Public Shared ReadOnly Property AppDisplayName() As String
                Get
                    Return ResourceManager.GetString("AppDisplayName", resourceCulture)
                End Get
            End Property

            ''' <summary>
            '''   Looks up a localized string similar to ShellGoBackButton.
            ''' </summary>
            Public Shared ReadOnly Property ShellGoBackButton As String
				Get
					Return ResourceManager.GetString("ShellGoBackButton", resourceCulture)
				End Get
            End Property

            ''' <summary>
            '''   Looks up a localized string similar to ShellHamburgerButtonName.
            ''' </summary>
            Public Shared ReadOnly Property ShellHamburgerButtonName As String
				Get
					Return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture)
				End Get
            End Property

            ''' <summary>
            '''   Looks up a localized string similar to NavigationDrawer.
            ''' </summary>
			Public Shared ReadOnly Property ShellNavigationDrawerPage As String
				Get
					Return ResourceManager.GetString("ShellNavigationDrawerPage", resourceCulture)
				End Get
			End Property
        End Class
    End Namespace
